[window]
padding.x = 5
padding.y = 5
opacity = 0.9
blur = true
decorations = "Full"
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

[selection]
save_to_clipboard = false

[env]
TERM = "xterm-256color"

## One Dark ##
# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
